In [8]:
import os 
os.chdir('../')
from utils.helper import generate_maze_with_objects,load_saved_map
import numpy as np 

In [2]:
map_plan,movable_kb,unknown_kb = generate_maze_with_objects(12,12,2,2,1)
map_plan

[['w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w'],
 ['w', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'w'],
 ['w', 'u', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'm', 'u', 'w'],
 ['w', 'u', 'i', 'c', 'c', 'c', 's', 'i', 'm', 'c', 'u', 'w'],
 ['w', 'u', 'c', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'w'],
 ['w', 'u', 'c', 'u', 'u', 'r', 'r', 'r', 'r', 'r', 'u', 'w'],
 ['w', 'u', 'c', 'u', 'u', 'r', 'u', 'o', 'u', 'r', 'u', 'w'],
 ['w', 'u', 'c', 'u', 'u', 'm', 'u', 'u', 'u', 'r', 'u', 'w'],
 ['w', 'u', 'c', 'u', 'u', 'm', 'u', 'u', 'u', 'r', 'u', 'w'],
 ['w', 'u', 'c', 'u', 'u', 'r', 'r', 'r', 'r', 'r', 'u', 'w'],
 ['w', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'w'],
 ['w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w']]

In [5]:
movable_kb

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0],
       [0, 1, 3, 1, 1, 1, 5, 3, 2, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 4, 4, 4, 4, 4, 1, 0],
       [0, 1, 1, 1, 1, 4, 1, 6, 1, 4, 1, 0],
       [0, 1, 1, 1, 1, 2, 1, 1, 1, 4, 1, 0],
       [0, 1, 1, 1, 1, 2, 1, 1, 1, 4, 1, 0],
       [0, 1, 1, 1, 1, 4, 4, 4, 4, 4, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [6]:
unknown_kb

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0],
       [0, 1, 2, 1, 1, 1, 5, 2, 2, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 4, 4, 4, 4, 4, 1, 0],
       [0, 1, 1, 1, 1, 4, 1, 6, 1, 4, 1, 0],
       [0, 1, 1, 1, 1, 2, 1, 1, 1, 4, 1, 0],
       [0, 1, 1, 1, 1, 2, 1, 1, 1, 4, 1, 0],
       [0, 1, 1, 1, 1, 4, 4, 4, 4, 4, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [7]:
np.argwhere(movable_kb == 5)[0]

array([3, 6])

In [9]:
MAP_PLAN,M_KB,U_KB = load_saved_map("/home/julian/git-repo/juliangdz/CausalCuriosityGDP/Search_And_Rescue_2D/causal_experiment_logs/maze_plan.pkl")

In [10]:
M_KB

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 6, 1, 4, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1,