In [6]:
import os 
os.chdir('../')
from utils.helper import generate_maze_with_objects,load_saved_map,read_config
import numpy as np 

In [7]:
CONFIG = read_config("/home/aaimscadmin/repos/Search_And_Rescue_2D/config.json")

In [8]:
np.array(CONFIG["environment"]["env_codes"]["room_array"])

array([['u', 'u', 'u', 'u', 'u', 'u', 'u'],
       ['u', 'r', '10', '11', '10', 'r', 'u'],
       ['u', '10', 'u', 'o', 'u', '10', 'u'],
       ['u', '11', 'u', 'u', 'u', '11', 'u'],
       ['u', '10', 'u', 'u', 'u', '10', 'u'],
       ['u', 'r', '10', '11', '10', 'r', 'u'],
       ['u', 'u', 'u', 'u', 'u', 'u', 'u']], dtype='<U2')

In [11]:
map_plan,movable_kb,unknown_kb = generate_maze_with_objects(20,20,20,20,20,0,1,CONFIG)
map_plan

[['w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w',
  'w'],
 ['w',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'u',
  'w'],
 ['w',
  'u',
  'c',
  'c',
  '00',
  '10',
  'c',
  '01',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  '10',
  'c',
  '00',
  'u',
  'w'],
 ['w',
  'u',
  '10',
  'c',
  'c',
  '10',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'u',
  'w'],
 ['w',
  'u',
  's',
  '01',
  '01',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  '00',
  'c',
  'c',
  'c',
  'c',
  'c',
  'u',
  'w'],
 ['w',
  'u',
  'c',
  'c',
  'c',
  'c',
  '00',
  'c',
  '01',
  'c',
  '01',
  'c',
  '01',
  'c',
  'c',
  'c',
  'c',
  'c',
  'u',
  'w'],
 ['w',
  'u',
  'c',
  'c',
  'c',
  'c',
  '01',
  '00',
  'c',
  '00',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'c',
  'u',
  'w

In [12]:
movable_kb

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 2, 4, 1, 3, 1, 1, 1, 1, 1, 1, 1, 4, 1, 2, 1, 0],
       [0, 1, 4, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 6, 3, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 2, 1, 3, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 3, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0, 4, 5, 4, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 2, 4, 1, 4, 1, 7, 1, 1, 3, 3, 1, 3, 1, 4, 4, 1, 1, 0],
       [0, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0],
       [0, 1, 2, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 1, 1, 3, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 4, 1, 1, 4, 1, 4, 1, 0],
       [0, 1, 3, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 4, 1, 1, 2, 1, 1, 3,

In [5]:
unknown_kb

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 6, 1, 1, 2, 2, 2, 1, 1, 0],
       [0, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 2, 2, 2, 0, 1, 1, 0],
       [0, 1, 2, 1, 2, 1, 7, 1, 2, 1, 1, 0],
       [0, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 0],
       [0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 0],
       [0, 1, 1, 1, 0, 2, 2, 2, 0, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [7]:
np.argwhere(movable_kb == 5)[0]

array([3, 6])

In [9]:
MAP_PLAN,M_KB,U_KB = load_saved_map("/home/julian/git-repo/juliangdz/CausalCuriosityGDP/Search_And_Rescue_2D/causal_experiment_logs/maze_plan.pkl")

In [10]:
M_KB

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 6, 1, 4, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1,